name: Build PDF Documentation

on:
  push:
    branches:
      - main
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

permissions:
  contents: write

jobs:
  build-integrate-pdf:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build PDF
        run: |
          cd doc/ibex/tgg/integrate-framework
          docker run --rm -v $PWD:/data maxkratz/pandoc-builder:latest ./md2pdf.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: integrate.pdf
          path: doc/ibex/tgg/integrate-framework/integrate-framework.pdf
